# Generated by Django 4.2.1 on 2024-02-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articles_link_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-time_created']},
        ),
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='articles',
            index=models.Index(fields=['-time_created'], name='articles_ar_time_cr_2201b1_idx'),
        ),
    ]
