# Generated by Django 4.2.1 on 2024-02-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articles_options_articles_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
