# Generated by Django 4.2.1 on 2024-03-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_photoproduct_product_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-time_created'], 'verbose_name': 'Продукты', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AddField(
            model_name='product',
            name='link_img',
            field=models.FileField(default=True, upload_to='product/', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PhotoProduct',
        ),
    ]
