# Generated by Django 4.2.1 on 2024-03-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': ['-time_created'], 'verbose_name': 'Карты', 'verbose_name_plural': 'Карты'},
        ),
    ]
